{% set name = "wcslib" %}
{% set version = "7.2" %}
{% set sha256 = "63959eb4859517a1ecca48c91542318bebeed62e4a1663656de9a983af376e39" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: ftp://ftp.atnf.csiro.au/pub/software/{{ name }}/{{ name }}-{{ version }}.tar.bz2
  sha256: {{ sha256 }}
  patches:
    - no-x-tests.patch  # avoid deluges of pgplot warnings

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - flex
  host:
    - cfitsio
    - pgplot 5.2.*  # [not win]
  run:
    - cfitsio
    - pgplot 5.2.*  # [not win]

test:
  commands:
    # Main validation performed in 'make check' stage
    - test -f $PREFIX/lib/libwcs$SHLIB_EXT

about:
  home: http://www.atnf.csiro.au/people/mcalabre/WCS/wcslib/
  license: LGPL-3.0-or-later
  license_file: COPYING.LESSER
  summary: 'Library for World Coordinate System computations'

extra:
  recipe-maintainers:
    - pkgw
