travis:
  secure:
    BINSTAR_TOKEN: uze+XgyacPu+JuIUd8cC/uWyYm+SHM5Irlx4HPA0B/vMPkR6yj0VBwR13M0ABKwJqTTsFHLJkIum2Gs8BNFxiS9zb6qhMoxbEe91VT3gaDer4hVGdT/x0kBmYIibypNpBU00Ia+pVDvmzo/xbCYHPsIADC/iPYl5sGcUdr1FPX1ei71REb+86Y5MaOwmmefEu3OEhsSBNL4ZGVpCXxkLrNM8OWx4KvBvnBu2OlygxK9zw1FpDnFMSvKIxZtJ/6Vj2IAykhK6COZyA5FFHyv8ldiDsVExirlZi1wOzAHINMpz+3ap9+lju2qKd4kDy5SOQOU28TBHptkLJwPQxOzJAdYJHmP7hrJtulPGA5PU5+87Ls5yv/NAwJ2RK355Gg17HMwg+yrYE4YVmP0JZFOBkSDSS4pDZ+J4ETTqDiiZbq60nGaMCt91pmc3AUzIzpWjg5V35ZOnTMXUeJvBA0S9L/YsOlX2zzvIamPbgrCmXq4kQHvIqW0yGg+oA80ADqreryVvBw6Ttz9e2WqRlxw5Sq6BqwoGB2CyD08Qnv3DGrU/qczUXUS4Z8BRnXNuggHrhj5h1fyx8Tj23LzfLRG2oyMGb1iJ6GTxTfAZVEtNZiQMQcaEtA9LohvgQwZeUe2zyKtrU6sxtoW8QqWf6OUHOGK48SvhqE2dPEv0xG5f0eE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
