appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: qQDJUiKtdhNQTSX7HeaIwzufu96k5b/E+HrBU/AFa6StJhxZPdq8/LrNNspEX3j4G7JZCk+PnAiCs8vm0wXvEEk5PCHzNatsTTbZYNtuOd9yhkgOY/KTnDB20IpunEyLf1uEU+4yQxNjwNLD1rUVuI9UszZoiRdQLRdcmOzWVsdTBV/UKnKOwj6b2lYxA9fl3UXOnKpH+9D3vlAO5OtbIR1LlTCCyykMtBPfeigeaOvq28vx9ua+Nodv8DMBSXWy1vJ8ujlKdLoXXxshymzsGiKFOK/rdR8JRYF1S+z/Xg7uK+Zn+hB7CIfw2SBQrVb31Bg8gZdpsOImov3THj1kQFdBonM7z/sMm1dbmNk5cFUU42++X6DfBTrP6sdeMtBVpmefaaOZ231+ZCFFUC37o5I82dRXE/yrHwXRqgpa0zR0abIBaP5Q6XmWEHNMunubjNmyamC1N+RBo7pd7gVSt4MZpykuGLBbwzg8Tqf92TmutwOs1lgD4hGPPyDZiRQWPeSmjbNhjYEwMtWliJ/+IEsUOjikZagpwEOh/vgRkgzhAY+sdWwLX9b9QfyPWmLObXpv/i5NgtQ5AdrPUTO2cDfbYFd8+YuAjpT14GUei3drxQOHO5+HotB9yo8t58V0+4uyhBdoPWCTZJiR1lTZipx9lu59ODwGEuAptV39uS0=}
